//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Extra/Input System/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""7f60838f-66a0-4068-98f9-cd799040d109"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Button"",
                    ""id"": ""39d937e5-4d30-43b5-b514-c154d3b3885c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""fbfec0ad-ffb5-400d-83fb-0df441542534"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftMouseAction"",
                    ""type"": ""Button"",
                    ""id"": ""72564894-abea-4aac-be67-1a10aa849f6a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightMouseAction"",
                    ""type"": ""Button"",
                    ""id"": ""c21376d4-6fa3-4d3d-82fb-e1c476b55deb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QAction1"",
                    ""type"": ""Button"",
                    ""id"": ""f7e9a92d-d3b1-4d0c-94a2-d58358ab0162"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EAction2"",
                    ""type"": ""Button"",
                    ""id"": ""d5c6df4c-065d-4ee7-a3c6-4fc03742c5e1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FAction3"",
                    ""type"": ""Button"",
                    ""id"": ""dc8f5763-b117-464c-b97f-087ba98a82d0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""606bba89-812c-4f38-aaba-a1479a787802"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7bb67bb7-ac6e-46db-b5d5-5663dc22601e"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ce5583b7-ee69-40ea-938a-51c2400cf662"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""2ce73e0a-8fe5-4fb9-afbf-0738ace9ec33"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""57497941-8f65-4d58-a928-6ec0558465e3"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrow Keys"",
                    ""id"": ""3343c286-329b-4a3a-90ba-be5d928f15e5"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e50b71d0-b61a-4851-a8e5-ce7bf240136c"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e5e798f6-cffa-4ccd-915b-eac0099044a2"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9ec3db25-e2d2-486f-b197-22867a3eaaf3"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""932cff59-b323-4a8d-a990-214d86eff2f9"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""ea251e76-b743-44df-bd8b-20639091fa23"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb669faa-04fb-46c1-bad2-6e21b7bf284c"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""LeftMouseAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f314127-c1dd-4e65-ab10-41c653a1c9b0"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard and Mouse"",
                    ""action"": ""RightMouseAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1657711b-37b0-4989-b9c7-8be5efe8fbb0"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QAction1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""06c7498e-12cb-40dc-9e14-fbddb93cc895"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EAction2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e1239230-c6aa-426b-95fa-3bd6a05449b2"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FAction3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard and Mouse"",
            ""bindingGroup"": ""Keyboard and Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_LeftMouseAction = m_Player.FindAction("LeftMouseAction", throwIfNotFound: true);
        m_Player_RightMouseAction = m_Player.FindAction("RightMouseAction", throwIfNotFound: true);
        m_Player_QAction1 = m_Player.FindAction("QAction1", throwIfNotFound: true);
        m_Player_EAction2 = m_Player.FindAction("EAction2", throwIfNotFound: true);
        m_Player_FAction3 = m_Player.FindAction("FAction3", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_LeftMouseAction;
    private readonly InputAction m_Player_RightMouseAction;
    private readonly InputAction m_Player_QAction1;
    private readonly InputAction m_Player_EAction2;
    private readonly InputAction m_Player_FAction3;
    public struct PlayerActions
    {
        private @Controls m_Wrapper;
        public PlayerActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @LeftMouseAction => m_Wrapper.m_Player_LeftMouseAction;
        public InputAction @RightMouseAction => m_Wrapper.m_Player_RightMouseAction;
        public InputAction @QAction1 => m_Wrapper.m_Player_QAction1;
        public InputAction @EAction2 => m_Wrapper.m_Player_EAction2;
        public InputAction @FAction3 => m_Wrapper.m_Player_FAction3;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Jump.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @LeftMouseAction.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftMouseAction;
                @LeftMouseAction.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftMouseAction;
                @LeftMouseAction.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeftMouseAction;
                @RightMouseAction.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightMouseAction;
                @RightMouseAction.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightMouseAction;
                @RightMouseAction.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightMouseAction;
                @QAction1.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnQAction1;
                @QAction1.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnQAction1;
                @QAction1.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnQAction1;
                @EAction2.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEAction2;
                @EAction2.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEAction2;
                @EAction2.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnEAction2;
                @FAction3.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFAction3;
                @FAction3.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFAction3;
                @FAction3.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnFAction3;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @LeftMouseAction.started += instance.OnLeftMouseAction;
                @LeftMouseAction.performed += instance.OnLeftMouseAction;
                @LeftMouseAction.canceled += instance.OnLeftMouseAction;
                @RightMouseAction.started += instance.OnRightMouseAction;
                @RightMouseAction.performed += instance.OnRightMouseAction;
                @RightMouseAction.canceled += instance.OnRightMouseAction;
                @QAction1.started += instance.OnQAction1;
                @QAction1.performed += instance.OnQAction1;
                @QAction1.canceled += instance.OnQAction1;
                @EAction2.started += instance.OnEAction2;
                @EAction2.performed += instance.OnEAction2;
                @EAction2.canceled += instance.OnEAction2;
                @FAction3.started += instance.OnFAction3;
                @FAction3.performed += instance.OnFAction3;
                @FAction3.canceled += instance.OnFAction3;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    private int m_KeyboardandMouseSchemeIndex = -1;
    public InputControlScheme KeyboardandMouseScheme
    {
        get
        {
            if (m_KeyboardandMouseSchemeIndex == -1) m_KeyboardandMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard and Mouse");
            return asset.controlSchemes[m_KeyboardandMouseSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnLeftMouseAction(InputAction.CallbackContext context);
        void OnRightMouseAction(InputAction.CallbackContext context);
        void OnQAction1(InputAction.CallbackContext context);
        void OnEAction2(InputAction.CallbackContext context);
        void OnFAction3(InputAction.CallbackContext context);
    }
}
